### ISSUE TITLE
Question about set t_Co=16

### ISSUE THREAD

**Issue by Lourens-Rich** [kronos29296/nvim-dotfiles#1]
In the https://github.com/neovim/neovim/wiki/FAQ says:

**Note:** Neovim ignores `t_Co` and other terminal codes.

Why do use it?

**Comment by kronos29296** [comment]
A result of me hacking to get solarized working on neovim at first but now it is useless (just leftover stuff after I refactored my entire config). In the end it was due some neovim bug and I just had to get another plugin for Solarized in neovim (Neosolarized). The line for terminal colors was never removed.

For neovim only thing for colors is `set termguicolors`
